[project]
name = "twitter-likes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "psycopg2",
    "requests",
    "twitter-openapi-python==0.0.41",
    "urllib3",
    "uvicorn>=0.34.3",
]
